### ISSUE TITLE
Replicating results

### ISSUE THREAD

**Issue by ClaudiaCuttano** [chenwei746/EEVG#2]
Hello and thank you for your work.
I am interested in replicating your results on the RIS task, with SwinB backbone in particular.
I noticed that you only report the command for evaluating with ViTDeT, so I had to guess the image size (it looks like 512 is the right one)
I used the following command, having download the Swin-B model from your OneDrive checkpoint folder, but I am getting a 55% IoU on RefCOCOg
`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port 12345 --use_env eval.py --batch_size 20 --num_workers 10 --bert_enc_num 12 --backbone SwinT --imsize 512 --dataset gref_umd --max_query_len 40 --eval_set test  --vl_enc_layers 3 --dim_feedforward 1024 --eval_model ./checkpoints/refcocog_SwinT/best_mask_checkpoint.pth --output_dir ./outputs/refcocog_swinT --is_segment --is_eliminate`

Moreover, I am getting the following mismatching keys when loading the checkpoint 
`unexpected key in source state_dict: norm.weight, norm.bias, head.weight, head.bias, layers.3.blocks.0.norm1.weight, layers.3.blocks.0.norm1.bias, layers.3.bl
ocks.0.attn.qkv.weight, layers.3.blocks.0.attn.qkv.bias, layers.3.blocks.0.attn.proj.weight, layers.3.blocks.0.attn.proj.bias, layers.3.blocks.0.norm2.weight, layers.3.blocks.0.norm2.bias, layers.3.blocks.0.mlp.fc1.weight, layers.3.blocks.0.mlp.fc1.bias, layers.3.blocks.0.mlp.fc2.weight, layers.3.blocks.0.mlp.fc2.b
ias, layers.3.blocks.1.norm1.weight, layers.3.blocks.1.norm1.bias, layers.3.blocks.1.attn.qkv.weight, layers.3.blocks.1.attn.qkv.bias, layers.3.blocks.1.attn.
proj.weight, layers.3.blocks.1.attn.proj.bias, layers.3.blocks.1.norm2.weight, layers.3.blocks.1.norm2.bias, layers.3.blocks.1.mlp.fc1.weight, layers.3.blocks
.1.mlp.fc1.bias, layers.3.blocks.1.mlp.fc2.weight, layers.3.blocks.1.mlp.fc2.bias, layers.3.blocks.0.attn.relative_position_index, layers.3.blocks.1.attn.rela
tive_position_index, layers.3.blocks.0.attn.relative_position_bias_table, layers.3.blocks.1.attn.relative_position_bias_table, layers.0.blocks.1.attn_mask, la
yers.1.blocks.1.attn_mask, layers.2.blocks.1.attn_mask, layers.2.blocks.3.attn_mask, layers.2.blocks.5.attn_mask, layers.2.blocks.7.attn_mask, layers.2.blocks
.9.attn_mask, layers.2.blocks.11.attn_mask, layers.2.blocks.13.attn_mask, layers.2.blocks.15.attn_mask, layers.2.blocks.17.attn_mask`

`missing keys in source state_dict: norm2.weight, norm2.bias, norm1.weight, norm1.bias, conv.0.weight, conv.0.bias, conv.1.weight, conv.1.bias, conv.1.running_
mean, conv.1.running_var, conv.4.weight, conv.4.bias, conv.5.weight, conv.5.bias, conv.5.running_mean, conv.5.running_var`

Can you provide any insights on what might be going wrong?

thanks in advance

**Comment by chenwei746** [comment]
Hi, thank you for your interest!
  Your evaluation command is right. The image size of 512 for Swin-B is consistent with Polyformer. The issue arose due to varying patch lengths for ViT and Swin-B, and I have resolved it. Simply pull the latest repository and reevaluate. Feel free to ask if you have any other questions!
