### ISSUE TITLE
你好，请教一下swin-transformer部分代码

### ISSUE THREAD

**Issue by Mr-Bigworth** [chenwei746/EEVG#3]
请问如果想把swin-b改成swin-s的话，是不是只要
arg = dict(pretrain_img_size=384, window_size=12, embed_dim=128, out_indices=[2, 1],
               depths=[2, 2, 18, 2], num_heads=[4, 8, 16, 32])
中dict这一块改成
dict(pretrain_img_size=224, window_size=7, embed_dim=96, out_indices=[2, 1],
               depths=[2, 2, 18, 2], num_heads=[3, 6, 12, 24])
类似这样就好，然后再加载swin-s的权重

**Comment by chenwei746** [comment]
Hi, 我已经在修改代码添加了Swin-S作为视觉Backbone，你可以拉取最新的代码，然后使用这个脚本来训练模型
```
 CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 \
 --master_port 12345 \
 --use_env train.py \
 --batch_size 20 \
 --lr 0.000025 \
 --lr_bert 0.000005 \
 --lr_visual 0.00001 \
 --aug_scale --aug_translate --aug_crop \
 --backbone SwinT-S --is_eliminate \
 --imsize 512 \
 --bert_enc_num 12 \
 --dataset gref_umd \
 --max_query_len 40 \
 --lr_scheduler poly \
 --is_segment \
 --vl_enc_layers 3 \
 --dim_feedforward 1024 \
 --loss_alpha 0.1 \
 --epochs 150 \
 --output_dir outputs/refcocog_SwinT-S
```

**Comment by Mr-Bigworth** [comment]
> Hi, 我已经在修改代码添加了Swin-S作为视觉Backbone，你可以拉取最新的代码，然后使用这个脚本来训练模型
> 
> ```
>  CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 \
>  --master_port 12345 \
>  --use_env train.py \
>  --batch_size 20 \
>  --lr 0.000025 \
>  --lr_bert 0.000005 \
>  --lr_visual 0.00001 \
>  --aug_scale --aug_translate --aug_crop \
>  --backbone SwinT-S --is_eliminate \
>  --imsize 512 \
>  --bert_enc_num 12 \
>  --dataset gref_umd \
>  --max_query_len 40 \
>  --lr_scheduler poly \
>  --is_segment \
>  --vl_enc_layers 3 \
>  --dim_feedforward 1024 \
>  --loss_alpha 0.1 \
>  --epochs 150 \
>  --output_dir outputs/refcocog_SwinT-S
> ```

好的，谢谢！ 我尝试一下
